[theme]
primaryColor = "#f5a270"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#eef4f4"
textColor = "#274c4d"
font = "sans serif"

[server]
headless = true
enableCORS = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
