[theme]
primaryColor = "#f5a270"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#eef4f4"
textColor = "#274c4d"
font = "sans serif"

[server]
headless = true
port = 5000
address = "0.0.0.0"
maxUploadSize = 200
enableXsrfProtection = false

[browser]
gatherUsageStats = false
