# Google OAuth Configuration
# Get these from Google Cloud Console (OAuth 2.0 Client ID)
# https://console.cloud.google.com/apis/credentials

GOOGLE_CLIENT_ID = "your-client-id.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "your-client-secret"
REDIRECT_URI = "https://your-repl-name.repl.co"
