# Google OAuth Configuration
# Get these from Google Cloud Console (OAuth 2.0 Client ID)
# https://console.cloud.google.com/apis/credentials

GOOGLE_CLIENT_ID = "your-client-id.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "your-client-secret"
REDIRECT_URI = "https://your-repl-name.repl.co"

# Optional: Tebi API Configuration
# TEBI_API_TOKEN = "your-tebi-api-token"
# TEBI_BOOKKEEPING_PATH = "/api/external/bookkeeping/export"

# Optional: Fallback accounts (if API doesn't work)
# [TEBI_ACCOUNTS]
# "447213" = "IBEO Demo Office"
